### ISSUE TITLE
Using latest beta throws an error when attempting to use pod_builder init

### ISSUE THREAD

**Issue by tareksabry1337** [Subito-it/PodBuilder#13]
Currently when trying to use the latest beta 24 on an existing project, running `pod_builder init` on it yields an error

<img width="1111" alt="Screen Shot 2020-09-03 at 2 02 12 PM" src="https://user-images.githubusercontent.com/45688300/92112443-1182b700-edee-11ea-8545-076574072283.png">

Environment:
* Xcode 11.5
* Cocoapods 1.9.3
* PodBuilder 2.0.0beta23

**Comment by tcamin** [comment]
Is this a react native project?

**Comment by tareksabry1337** [comment]
Nope, native.

**Comment by tcamin** [comment]
My bad again, will fix later today.
