### ISSUE TITLE
Building progress

### ISSUE THREAD

**Issue by gutaker** [Subito-it/PodBuilder#19]
It would be nice to see which `Pod` is compiling at the moment or any progress at all.
Right now it's just `Skipping User Project Integration` and empty line.

`pod-builder (2.0.0.beta.31, 1.9.4)`

**Comment by tcamin** [comment]
Pods are built all together (there might be dependencies between pods), so this is really not possible

**Comment by gutaker** [comment]
I understand, thank you. So maybe a simple line like `Prebuilding Pods...`, just to give user an info on whats actually happening?
