### ISSUE TITLE
Turn into a CocoaPods plugin?

### ISSUE THREAD

**Issue by orta** [Subito-it/PodBuilder#2]
👋 this appeared in my twitter stream a few times recently, and I'd love to get this into this document on the CP guides: https://guides.cocoapods.org/plugins/pre-compiling-dependencies.html

Ideally though, it would need to be a CocoaPods plugin so that it can fit into that section - maybe the build ones could hijack the pre-installer and exit(0) after your pre-built versions are done? I'm unsure, I've not used it.

**Comment by tcamin** [comment]
Hi! As much as I'd love that PodBuilder gets included in the guide I fear the way its designed doesn't really fit with the plugin concept. PodBuilder is a wrapper over CocoaPods-Core and uses the CocoaPods-Rome plugin to generate dSYM and prebuilt frameworks. Ideally in a project that uses PodBuilder you should be able to manage your pod dependencies using pod_builder only.

Compared to CocoaPods-Binary it definitely has some overhead as it generates additional support files but all confined in a separate folder which allows an easy deintegrate process, if one decides to stop using it. It may look harder to use at first but the added overhead, on the other hands, allows some more fine grain control on per pod build settings, podspec ovverride and some advanced features like the [install_source](https://github.com/Subito-it/PodBuilder#install_sources-command) which allows to step into prebuilt code during debugging.

That said, I'm no expert of CocoaPods plugin development so I'll definitely take a look if I there's any way to make it fit in that space. I'll leave the issue open till then.

**Comment by tcamin** [comment]
Will close this issue because PodBuilder evolved in a way where it makes sense for it to be a standalone tool. Thanks a lot for the interest though!
