### ISSUE TITLE
Generic 3rd party issues

### ISSUE THREAD

**Issue by dcristolovean** [Subito-it/PodBuilder#21]
This is more of an FYI, but I thought it might be interesting to write here various issues with different Pods and pod builder.

Since I had to run pod_builder build_all again, I run into a new set of issues, this time with "abseil".  This is a c++ lib used by... not sure, probably Firebase or some other Google pod.
What I noticed, in the abseil.podspec file in the Prebuilt folder, there are a ton of errors like this:

p1.subspec 'algorithm' do |p2|
            p3.vendored_frameworks = 'absl.framework'
            p3.dependency 'abseil/base/config'
    end

As you can see, it should be p2 inside, not p3.  The file is full of such mistakes.  I tried to correct them by hand and re-run build all but then it complained again it can't find the abseil/strings/str_format dependency. 
So I gave up and put the abseil in the skip_pods section.  That worked OK and the build_all finished.  Abseil was installed in /Pods as intended.

Is this something fixable?

**Comment by tcamin** [comment]
Should be fixed in 2.1.1
