### ISSUE TITLE
Add support for Mac Catalyst

### ISSUE THREAD

**Issue by ky1vstar** [Subito-it/PodBuilder#22]
Hi, I really love how good your tool works compared to `cocoapods-binary`. I've successfully integrated `PodBuilder` to my project and building for iOS works just fine. But when I try to build my project for macOS (Mac Catalyst) it fails, because Xcode cannot find x86-64 for macOS (it manages to find iPhoneSimulator only). `build_xcframeworks` flag is enabled

**Comment by tcamin** [comment]
Try installing latest beta:

```
> git clone -b feature/catalyst_support https://github.com/Subito-it/PodBuilder.git
> cd PodBuilder
> sudo rake install
```

Now you can try to rebuild all (you may need to pass the --force flag),  PodBuilder should autodetect if the project supports catalyst and build accordingly.

I tried on a minimal sample project and it works, please if you try it out let me know if it works on your end as well
