### ISSUE TITLE
Unable to build RealmSwift

### ISSUE THREAD

**Issue by anlaital** [Subito-it/PodBuilder#23]
I'm trying out PodBuilder and running into issues when trying to build [RealmSwift](https://github.com/realm/realm-cocoa). The error given is as follows:

```
`RealmSwift` does not specify a Swift version and none of the targets (`DummyTarget`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

Is there an easy workaround for this that you know of?

**Comment by tcamin** [comment]
See the FAQ: https://github.com/Subito-it/PodBuilder#i-get-an-podwitherror-does-not-specify-a-swift-version-and-none-of-the-targets-dummytarget-when-building
