### ISSUE TITLE
How can i build local pod ? 

### ISSUE THREAD

**Issue by ebanstev** [Subito-it/PodBuilder#26]

**Comment by tcamin** [comment]
Just point to the local path in the PodBuilder's Podfile

for example:

```pod 'mylocalpod', :path => 'relative_path_to_the_folder_containing_the_local_podspec'```

**Comment by ebanstev** [comment]
> Just point to the local path in the PodBuilder's Podfile
> 
> for example:
> 
> `pod 'mylocalpod', :path => 'relative_path_to_the_folder_containing_the_local_podspec'`

@tcamin i did to try this solution, but it's not work.

**Comment by tcamin** [comment]
We do use PodBuilder with local pods, so it should work. More details or a sample project might help to better understand the problem.

**Comment by ebanstev** [comment]
@tcamin I see, thanks. I will close this issue.
