### ISSUE TITLE
Issue with APPSync and AWSCore

### ISSUE THREAD

**Issue by dcristolovean** [Subito-it/PodBuilder#27]
Hi, I added AWSAppSync in my Pods and there are 2 minor issues, but they hinder our automatic processes by adding a manual step/fix.
After pod_builder, there are 2 values in the Pods project/AWSAppSync that are wrong:

- iOS Deployment Target is set to iOS 9 and I need it to iOS 10
- Enable Bitcode is set to YES (in both AWSAppSync and AWSCore).   I do have the ENABLE_BITCODE to NO globally in the json file and no other pod is set to YES besides those 2

"AWSAppSync": {
      "ENABLE_BITCODE": "NO",
      "IPHONEOS_DEPLOYMENT_TARGET": "10.0"
    },
    "AWSCore": {
      "ENABLE_BITCODE": "NO"
    }

I added these to my json but they do not work.

Any ideas ? Thanks !

**Comment by return-main** [comment]
Hi @tcamin,
I created a minimal reproduction repository to demonstrate the bug:
https://github.com/return-main/PodBuilder-build_settings_overrides-bug

**Comment by tcamin** [comment]
I've updated the documentation to clarify that the BUILD_SETTINGS refer to the settings used when compiling prebuilt items and are not used when integrating the project (when no building occurs anymore).

Wrt to deployment target PB should honour the one specified in the Podfile. As far as I can tell it does in the sample project you provided.

Anyhow a simple fix is to modify those settings in the post_install hook in your app's Podfile.

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|  
            if target.name == "AWSCore"
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            end
    
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
```

**Comment by tcamin** [comment]
Let me know if this is enough to close the issue.

**Comment by return-main** [comment]
@dcristolovean must have missed the notification. It's okay I'm his colleague.

Thank you very much for the code snippet, it solved our problems !
You can close this issue now 👍
