### ISSUE TITLE
[Question] What is best way for using script of FirebaseCrashlytics(run/upload-dsym)

### ISSUE THREAD

**Issue by knchst** [Subito-it/PodBuilder#36]
When I use Pod-Builder to building FirebaseCrashlytics, a source of FirebaseCrashlytics is not downloaded in `./Pods` directory. 
What is best way for using script of FirebaseCrashlytics(run/upload-dsym)

https://firebase.google.com/docs/crashlytics/get-started#initialize-crashlytics

**Comment by tcamin** [comment]
We have a script as part of our release pipeline which downloads the versioned executables of run and upload-symbols to /usr/local/bin as follows

- We parse "PodBuilder/Prebuilt/FirebaseCrashlytics/PodBuilder.json" and extract the installed `version`
- We download "https://raw.githubusercontent.com/firebase/firebase-ios-sdk/#{version}/Crashlytics/run" to /usr/local/bin/crashlytics/run
- We download "https://raw.githubusercontent.com/firebase/firebase-ios-sdk/#{version}/Crashlytics/run" to /usr/local/bin/crashlytics/upload-symbols

Once submission is performed we the downloaded executables to upload symbols

**Comment by knchst** [comment]
> We have a script as part of our release pipeline which downloads the versioned executables of run and upload-symbols to /usr/local/bin/crashlytics as follows

Where is the script ?

**Comment by tcamin** [comment]
The script is part of our (@Subito-it) internal release pipeline which is not public. If automating this is not an option you can:
- Add FirebaseCrashlytics to the [skip_pods](https://github.com/Subito-it/PodBuilder#skip_pods) list. The binaries should be checked out to the usual location under Pods.
- manually download the upload-dsym binary from the firebase repo with the aforementioned links

**Comment by knchst** [comment]
@tcamin Thanks. I understand!

**Comment by ast3150** [comment]
I was having the same issue and created a Ruby script to download the binaries as described. I'm calling it from the `post_install` actions in the Podfile. (See example in Gist)

https://gist.github.com/ast3150/e87d3e0710393dabab882466fc6f985d
