### ISSUE TITLE
Failed with `PodBuilder::Command::Build#should_build_catalyst` when `integrate_targets: false`.

### ISSUE THREAD

**Issue by knchst** [Subito-it/PodBuilder#39]
![image](https://user-images.githubusercontent.com/13914484/119654122-121f1a00-be63-11eb-85c2-3bba82107b33.png)

ref: https://github.com/CocoaPods/CocoaPods/blob/123f2d02f42075fa9f3b1bc729b342bd844efb44/lib/cocoapods/installer/analyzer.rb#L511

**Comment by tcamin** [comment]
Could you provide a sample project that replicates the issue? It would ease debug the issue.

Thanks

**Comment by knchst** [comment]
[PodBuilderTest.zip](https://github.com/Subito-it/PodBuilder/files/6553142/PodBuilderTest.zip)

**Comment by knchst** [comment]
@tcamin

[PodBuilderTest.zip](https://github.com/Subito-it/PodBuilder/files/6553166/PodBuilderTest.zip)

Here's a sample project 🙏

and I created Sample Pull Request to fix this issue. #41
