### ISSUE TITLE
After install, pod_builder shows 'command not found'

### ISSUE THREAD

**Issue by buptwsg** [Subito-it/PodBuilder#43]
Hi,
   I use command 'sudo gem install pod-builder' to install, and it shows that pod builder is installed successfully. But when I execute any command, it tells me that '-bash: pod_builder: command not found'.
  
 ruby --version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
 which ruby : /usr/local/opt/ruby/bin/ruby

 Please help me, thanks!

**Comment by tcamin** [comment]
Sorry for the late reply however this sound more like a ruby installation issue than something PodBuilder specific.
