### ISSUE TITLE
`build` command ignores fixed version

### ISSUE THREAD

**Issue by funzin** [Subito-it/PodBuilder#44]
I added some library(e.g Alamofire) to `Podifle` and then executed `pod_builder build Alamofire`.

Podfile
```
use_frameworks!
target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for SampleApp
  pod 'Alamofire', '5.0.0'
  pod 'LibraryA'
  pod 'LibraryB'

end
```

After that, I removed version code from Podfile and then executed `pod_builder build Alamofire`.
```
use_frameworks!
target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for SampleApp
  pod 'Alamofire'
  pod 'LibraryA'
  pod 'LibraryB'
end
```
I want to keep Alamofire as version 5.0.0 but Alamofire was updated to 5.4.3😕

In Addtion, if `LibraryA` lastest tag is updated, LibraryA is also updated😱(I don't update `LibraryA`)
Can you give me some advice to resolve this problem?

**Comment by tcamin** [comment]
When you invoke `pod_builder build Alamofire` you are explicitly requesting to rebuild Alamofire which will rebuild latest version because it works as `pod update` does. My suggestion is to keep pinning the version as in your first example.

Regarding the second issue, does LibraryA depend on Alamofire?

**Comment by funzin** [comment]
Thank you for your replay!

>Regarding the second issue, does LibraryA depend on Alamofire?
No, it doesn't. it works as `pod update`

> My suggestion is to keep pinning the version as in your first example.
I want the behavior like `pod install`(`pod install` doesn't change my library version if Podfile.lock exists)
Is it difficult with PodBuilder?
