### ISSUE TITLE
Facebook SDK issues

### ISSUE THREAD

**Issue by dcristolovean** [Subito-it/PodBuilder#52]
Hi, for some unknown reasons the Facebook SDK suddenly doesn't get pre-built.
It's placed in /Pods and although this shouldn't be much of a deal, I'm getting tons of errors about it not finding various FB classes and methods.  
Seems that somehow the sdk is not prebuilt but all the settings for it point in the wrong direction.

Can you please take a look, latest FB SDK ?

**Comment by tcamin** [comment]
Does this occur on an empty project that integrates only the FB SDK?
