### ISSUE TITLE
Podbuilder is not working with react-native version 68.1

### ISSUE THREAD

**Issue by habiiev** [Subito-it/PodBuilder#62]
This is the error I am getting:
<img width="280" alt="Screenshot 2022-04-26 at 17 35 25" src="https://user-images.githubusercontent.com/31899678/165324786-44b2a745-63cc-4b09-9436-749dfed2b67e.png">

It's related to [this](https://github.com/facebook/react-native/issues/32432) react-native issue

To reproduce just create an empty react-native project, install any dependency that has native ios code and then configure pod-builder:

Steps to reproduce:

1. `npx react-native init rnapp`
2. `cd rnapp`
3. `npm install react-native-reanimated --save`
4. `cd ios`
5. `pod_builder init`
6. ` pod_builder build_all`

Without pod builder, everything works fine right now

I don't really know where to look for the cause of this error, I would be glad to help if you could point me in the correct direction :)

Versions:
Xcode 13.3.1
pod_builder 4.4.1
Builds for ios 11 and 14

@tcamin could you help me with this?

**Comment by habiiev** [comment]
We are assuming that this is related to the new architecture with turbomodules

**Comment by tcamin** [comment]
Just a quick update: I've been taking a look at the compilation issues and found a way to make things work. I hope to be able to share something next week.

**Comment by tcamin** [comment]
I've pushed the changes to the`rn_68` branch. You can try the update as follows:

```
git clone -b hotfix/rn_68 https://github.com/Subito-it/PodBuilder.git
cd PodBuilder
sudo rake install
```

Out of curiosity I tried clean build times and results look really good!
without PB 190s
with PB 61s
