### ISSUE TITLE
Fail to build with "Resolver" / "Mocker" / "Reusable"

### ISSUE THREAD

**Issue by huihuang82** [Subito-it/PodBuilder#74]
Hi, 

when I use podBuilder, the prebuilt runs well, but when I tried to build my project, the following error occurs:

I guess it's because the library `Resolver` has a class with the same name
the same issue occurs also for library `Mocker` / `Reusable`, and they all has a class with the same name of the library.

<img width="1278" alt="image" src="https://github.com/Subito-it/PodBuilder/assets/95685673/cf858c08-b380-41e6-a5f1-0b315cba8bff">

libraries links:
https://github.com/hmlongco/Resolver
https://github.com/WeTransfer/Mocker

**Comment by tcamin** [comment]
Yes, that's the problem. For more info see this [issue](https://github.com/apple/swift/issues/56573).

That being said, you have 2 options:
1. Manually fix swiftinterfaces from your Podfile:
```
post_install do |installer|
    base_path = `git rev-parse --show-toplevel`.strip
    swift_interface_paths = Dir.glob("#{base_path}/PodBuilder/Prebuilt/Resolver/**/*.swiftinterface")
    swift_interface_paths.each do |path|
        content = File.read(path)
        content.gsub!('Resolver.', '')
        File.write(path, content)
    end

    ... same for other frameworks
end
```

2. Add the `-Xfrontend -module-interface-preserve-types-as-written` to OTHER_SWIFT_FLAGS build options.

The first option is more reliable and I would personally suggest it, although it requires to replicate the same approach for all frameworks having a type with the same name of the class.

**Comment by huihuang82** [comment]
it works!
