### ISSUE TITLE
"pre-download" of some pod occurs everytime

### ISSUE THREAD

**Issue by huihuang82** [Subito-it/PodBuilder#75]
I noticed that some of my libraries is downloaded everytime I run `pod_builder build_all` (while this issue doesn't occur when I run `pod install` before).
those libraries has some common points:
1. they're all my private pod, I'm using `:tag` to reference them
2. they're all just contains binary `.a` file or asset files. they don't contain source code.

since we're using circleCI, I don't want the pod source file to be downloaded everytime. (BTW if I could specify the download folder, I could use circleCI's cache to walk around it)

<img width="1376" alt="image" src="https://github.com/Subito-it/PodBuilder/assets/95685673/b1e65c1c-855d-450c-a05b-ab915ca95929">

**Comment by tcamin** [comment]
If those libraries are dependencies of other pods it is expected for
PodBuilder to download them, since they are required to compile things
correctly. On the other hand if they are used only by your main target you
can manually add them to the skip_pods key in the PodBuilder.json file.
