### ISSUE TITLE
[Question] is the prebuilt lib's dsym get merged when I create a release build

### ISSUE THREAD

**Issue by huihuang82** [Subito-it/PodBuilder#78]
we're using sentry for crash analysis. 

currently I'm not sure if the prebuilt lib's crash will be symbolized

**Comment by huihuang82** [comment]
you mean, if I have `n` prebuilt libs, I upload the n dsyms seperately?

**Comment by tcamin** [comment]
Yes, all dsyms need to be uploaded on every new release

**Comment by huihuang82** [comment]
thanks!
